### ISSUE TITLE
Things for v6

### ISSUE THREAD

**Issue by GregCampbellPresents** [AngelGryph/MadeInHeaven_SpellPack#9]
Greetings, @AngelGryph!

Tonight for me was bug hunting in your spell pack.  I'm glad that certain things I reported were fixed, and I found many more things on which to comment in the link below.

Results: https://docs.google.com/document/d/10PZInbjvVChGnQefWP-3cIxvqfo32UL2pc5_mTtDCAM/edit?usp=sharing

Thankee and enjoy!

**Comment by AngelGryph** [comment]
My, you have been busy.  First of all, thanks for your efforts.  I can't guarantee everything will be addressed or used, but I appreciate the input anyway.

Anyway, there are a couple of things I think I can address quickly.

In general:
- I do not currently know how to create additional status icons.  While this is a "nice to have", it currently doesn't have a high priority and I can't guarantee it will be there anytime soon especially since I first have to figure out how it even works at all.
- My spell descriptions are written in the same style as the vanilla spells in BG(2)EE (in fact copied and edited, for spell similar to vanilla spells).  I don't know or care how SR does things; I do things my way and have no desire to emulate or replace SR.
- I do not currently plan to have Mass versions of any other spells, Mass Negative Plane Protection was explicitly a nod to Order of the Stick.  However, I am giving some thought to implementing 3.5e style Bear's Endurance, Bull's Strength (replacing Strength) and Cat's Grace which may or may not include their mass versions.

Ball Lighting: Exactly what is not clear about "The caster gets one orb for every five levels, with a maximum of four at level 20."?  It's exactly that, one ball lightning for every fifth caster level.

Blink: The description states exactly what the spell does, teleport (or "blink") the caster rapidly over the battlefield, making them more tricky to engage in melee.  It's a defence somewhat similar in approach to Teleport Field.

Faerie Sword: It creates a weapon in the caster's hand, nothing more and nothing less.  It doesn't do anything at all with invisibility or mislead.  Note that the secondary effects of striking with the faerie sword are completely random.  It's essentially a wand of wonder in sword form, and one of the possible effects is disintegrating the target.

Iron Maiden: The personal range is deliberate.  That is how the spell is supposed to work.

Lesser/Greater Malison: I do not change Greater Malison at all.  Lesser Malison has exactly the same effect as its big brother except that the save penalty is only -2 instead of -4.  (They are  by design cumulative with each other.)

Sleep/Slumber: I do not change Sleep at all.  Sleep targets an area, not a creature, and affects only the caster's enemies in said area; this is its vanilla behaviour.  Neutrals are not considered enemies to party members and thus won't be affected.  Slumber behaves exactly like Sleep except it can affect creatures with up to 9 hd.  (PW: Sleep works on neutrals because it is cast directly at a creature instead of being an area effect.)

Starfire: This spell didn't work out the way I liked it and is deprecated.  It was basically a lesser version of Meteor Swarm that did less damage and allowed a save.
